import DeteilsSectionContainer from "@/components/DeteilsSectionContainer";


export default function AppFunctionality() {
    return (
        <DeteilsSectionContainer>
            <h1 className='text-4xl font-medium text-center md:text-start'>App functionality</h1>
            <h2 className="my-5 md:my-10 text-2xl text-black font-medium">User registration</h2>
            <p className='mt-10 md:grid grid-cols-3'><span className='col-span-2'>Andersen designed and implemented a registration flow catered to the needs of doctors and patients, ensuring compliance with HIPAA and other data protection regulations.</span></p>
            <h2 className="my-5 md:my-10 text-2xl text-black font-medium">Dashboard management</h2>
            <p className='mt-10 md:grid grid-cols-3'><span className='col-span-2'>Since any treatment of skin conditions is universally based on individual cases, having a customizable dashboard is also essential for medical professionals using this solution. <br />
            Therefore, our healthcare IT experts ensured a dashboard management capability, allowing users to manage the main page of the dashboard according to the available settings. <br />
            Among other things, it enables medical professionals to add data and control the post-care stage (after the treatment is finished). On top of that, one can search for care receivers via the main page by names/emails/phone numbers. It is also possible to filter them by required parameters. All applicable parameters are divided into three sections, with a multiselection capability also available.</span></p>
            <h2 className="my-5 md:my-10 text-2xl text-black font-medium">Notifications</h2>
            <p className='mt-10 md:grid grid-cols-3'><span className='col-span-2'>Adherence to care routines is key. With this priority in mind, our experts added notifications to the solution's range of functionalities. These notifications remind users of the steps to be taken, following the care recommendations. <br /> 
            Other notifications inform medical professionals about developments requiring their attention and their daily responsibilities regarding various treatment plans, ensuring they provide better care and miss nothing of importance.</span></p>
            <h2 className="my-5 md:my-10 text-2xl text-black font-medium">User profiles</h2>
            <p className='mt-10 md:grid grid-cols-3'><span className='col-span-2'>Treatment of various skin conditions remotely involves handling large quantities of patient information. In order to handle this challenge, our tech experts developed a comprehensive system of user profiles. The latter give the possibility to add, store, analyze, and use every needed piece of care data. <br />
            The following sections can be found in the profiles:</span></p>
            <ul className='md:grid grid-cols-2 mt-10'>
                <li className='flex gap-3'>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4lYWyrh5v1ik0aDNEHA6RYW4PLHYtzgH3xg&usqp=CAU" alt="" className='w-[23px] h-[20px]'/>
                    <span>User profile picture;</span>
                </li>
                <li className='flex gap-3'>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4lYWyrh5v1ik0aDNEHA6RYW4PLHYtzgH3xg&usqp=CAU" alt="" className='w-[23px] h-[20px]'/>
                    <span>Personal data section;</span>
                </li>
                <li className='flex gap-3'>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4lYWyrh5v1ik0aDNEHA6RYW4PLHYtzgH3xg&usqp=CAU" alt="" className='w-[23px] h-[20px]'/>
                    <span>Various statuses, statistics, and options to change medical data according to the current state of the patient's skin;</span>
                </li>
                <li className='flex gap-3'>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4lYWyrh5v1ik0aDNEHA6RYW4PLHYtzgH3xg&usqp=CAU" alt="" className='w-[23px] h-[20px]'/>
                    <span>Capability to upload relevant medical documents.</span>
                </li>
            </ul>
            <p className='mt-10 md:grid grid-cols-3'><span className='col-span-2'>Therefore, medical professionals are in the right position to view health histories and diagnosis-related information, compare treatment results, and update treatment plans depending on the recommendations generated by advanced algorithms. </span></p>
            <p className='md:grid grid-cols-3'><span className='col-span-2'> 
            The platform enables specialists to select the most effective treatment plans based on diagnostic results. In this fashion, the system helps to identify the most appropriate cosmeceuticals by displaying available products with data tags, divided into sections. </span></p>
            <p className=' md:grid grid-cols-3'><span className='col-span-2'>
            The system also keeps a record of care recommendations, estimates the duration of a prescribed care plan, and tracks the user's skin care journey. 
            As a result, proper care is received, while medical specialists can conveniently and seamlessly work on their cases.</span></p>
            <h2 className="my-5 md:my-10 text-2xl text-black font-medium">Solution</h2>
            <p className=' md:grid grid-cols-3'><span className='col-span-2'>
            In close cooperation with our analysts and software engineers, the skin care business has obtained a cutting-edge data-driven skin software tool for its users. Thanks to the personalized capabilities, the average duration required for treating a user's skin condition is reduced to a mere 5-6 weeks. Consequently, this has led to increased client loyalty and satisfaction rates, enabling the company to generate higher revenue and attract more customers.</span></p>
            <h2 className="my-5 md:my-10 text-2xl text-black font-medium">Project results</h2>
            <ul className='md:grid grid-cols-2 mt-10'>
                <li className='flex gap-3 pb-5 items-centernp'>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4lYWyrh5v1ik0aDNEHA6RYW4PLHYtzgH3xg&usqp=CAU" alt="" className='w-[18px] h-[15px]'/>
                    <span>The launch of a customized online store;</span>
                </li>
                <li className='flex gap-3 pb-5 items-centernp'>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4lYWyrh5v1ik0aDNEHA6RYW4PLHYtzgH3xg&usqp=CAU" alt="" className='w-[18px] h-[15px]'/>
                    <span>A more stable and reliable system;</span>
                </li>
                <li className='flex gap-3 pb-5 items-centernp'>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4lYWyrh5v1ik0aDNEHA6RYW4PLHYtzgH3xg&usqp=CAU" alt="" className='w-[18px] h-[15px]'/>
                    <span>A new library applied to the admin panel;</span>
                </li>
                <li className='flex gap-3 pb-5 items-centernp'>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4lYWyrh5v1ik0aDNEHA6RYW4PLHYtzgH3xg&usqp=CAU" alt="" className='w-[18px] h-[15px]'/>
                    <span>Integration with a CRM system;</span>
                </li>
                <li className='flex gap-3 pb-5 items-centernp'>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4lYWyrh5v1ik0aDNEHA6RYW4PLHYtzgH3xg&usqp=CAU" alt="" className='w-[18px] h-[15px]'/>
                    <span>A delivery tracking system added, and a system for consumer reviews delivered;</span>
                </li>
                <li className='flex gap-3 pb-5 items-centernp'>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4lYWyrh5v1ik0aDNEHA6RYW4PLHYtzgH3xg&usqp=CAU" alt="" className='w-[18px] h-[15px]'/>
                    <span>Full compliance with GDPR, HIPAA, and PIPEDA ensured;</span>
                </li>
                <li className='flex gap-3 pb-5 items-centernp'>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4lYWyrh5v1ik0aDNEHA6RYW4PLHYtzgH3xg&usqp=CAU" alt="" className='w-[18px] h-[15px]'/>
                    <span>Integration with third parties ensured, including online payment systems;</span>
                </li>
                <li className='flex gap-3 pb-5 items-centernp'>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4lYWyrh5v1ik0aDNEHA6RYW4PLHYtzgH3xg&usqp=CAU" alt="" className='w-[18px] h-[15px]'/>
                    <span>Thorough redesign of the system with an extension of its functionalities.</span>
                </li>
            </ul>
        </DeteilsSectionContainer>
    );
}